<?php
/*
 * Function hook_init()
 */
function domainsso_init() {
	if(isset($_SESSION['domainsso_user_login']) && $_SESSION['domainsso_user_login'] && arg(0) != 'domainsso'){
		drupal_add_js(drupal_get_path('module', 'domainsso').'/domainsso.js');
		
		$current = domain_get_domain();
		$domains = domain_list_by_machine_name();
		
		$data = array();
		$curdomainurl = '';
		foreach($domains as $domain){
			if($current['domain_id'] != $domain['domain_id']){
				$data[] = $domain['path'].'?q=domainsso/sync&sid=' . session_id() . '&r=' . time() . '&hash=' . md5(session_id() . drupal_get_hash_salt());
			}else{
				$curdomainurl = url('domainsso/synced', array('query' => array('r' => time())));
			}
		}
		
		drupal_add_js(array('domainsso' => array('domains' => $data, 'curdomain' => $curdomainurl)), 'setting');
	}
}

/*
 * Function hook_menu()
 */
function domainsso_menu() {
  $items['domainsso/sync'] = array(
    'page callback' => 'domainsso_sync_page',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );
  
  $items['domainsso/synced'] = array(
    'page callback' => 'domainsso_synced_page',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

function domainsso_synced_page() {
	unset($_SESSION['domainsso_user_login']);
}

function domainsso_sync_page() {
	header('Content-Type: application/javascript');
	
	$src_sid = $_GET['sid'];
	$hash = $_GET['hash'];
	if ($hash == md5($src_sid . drupal_get_hash_salt())) {
  	$uid = db_query("select uid from {sessions} where sid=:sid", array(':sid' => $src_sid))->fetchField();
  	if($uid) {
  		global $user;
  		$user = user_load($uid);
  		drupal_session_regenerate();
  	}
  }
}

/*
 * Function hook_user_login()
 */
function domainsso_user_login(&$edit, $account) {
	$_SESSION['domainsso_user_login'] = TRUE;
}

/*
 * Function hook_user_logout()
 * Unset all user's other sessions.
 */
function domainsso_user_logout($account) {
	$sid = session_id();
	global $user;
	
	db_query("delete from {sessions} where uid=:uid and sid != :sid", array(':uid' => $user->uid, ':sid' => $sid));
}